news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from report.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('news_item/<int:id>/', item_news, name="item_news"),
    path('filter/<str:slug>/', filter_news, name="filter_news"),
    path('filter_by_tags/<int:id>/', filter_news_by_tags, name="filter_news_by_tags"),
    path('search/', search_news, name="search_news"),

    path('my_news/', my_news, name='my_news'),
    path('my_news/create/', create_news, name='create_news'),
    path('my_news/<int:id>/delete/', delete_news, name='delete_news'),
     path('my_news/<int:id>/update/', update_news, name='update_news'),

    path('login/', login_profile, name='login'),
    path('logout/', logout_profile, name='logout'),
    path('registration/', registration, name='registration'),
    
    path('api/', include('report.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Count
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
import os

class Categories(models.Model):

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    slug = models.SlugField(unique=True, verbose_name='slug название', null=True)
    title = models.CharField(max_length=100, verbose_name='название категотрии')

    def __str__(self):
        return f'{self.title}'


class Tags(models.Model):
    
    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'

    title = models.CharField(max_length=100, verbose_name='название тега')

    def __str__(self):
        return f'{self.title}'


class News(models.Model):

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
    
    title = models.CharField(max_length=300, verbose_name='заголовок')
    image = models.ImageField(verbose_name='изображение', upload_to='images/', null=True)
    category = models.ForeignKey('Categories', on_delete=models.PROTECT, null=True, verbose_name='категория')
    tags = models.ManyToManyField('Tags', verbose_name='теги')
    content =  models.TextField(verbose_name='контетн')
    date = models.DateField(verbose_name='дата добавление', auto_now_add=True)
    views = models.PositiveIntegerField(verbose_name='просмотры', default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор', null=True)


    def __str__(self):
        return f'{self.title}'


@receiver(post_save, sender=News)
def viewer_singnals(sender, instance, created, **kwargs):
    if created:
        instance.views = 11
        instance.save()

@receiver(post_delete, sender=News)
def delete_file_singnals(sender, instance, **kwargs):
        os.remove(instance.image.path)

templates/my_news/create_news.html
{% extends 'base.html' %}
{% block title %}| Добавление новостей{% endblock title %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container py-5">  
        <h3 class="mb-5 text-center">Добавление новостей</h3>

        <form action="{% url 'create_news' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-12 mb-3">
                    <label for="id_title">Заголовок <span class="text-danger">*</span></label>
                    <input type="text" name="title" id="id_title" class="form-control" required>
                </div> 
                <div class="col-md-6 col-12">
                    <label for="id_iamge">Изображение <span class="text-danger">*</span></label>
                    <input type="file" name="image" class="form-control" id="id_iamge" required>
                </div>
                <div class="col-md-6 col-12">
                    <label for="id_category">Категория <span class="text-danger">*</span></label>
                    <select name="category" class="form-control" id="id_category required">
                        <option disabled selected>Выберите категорию</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-12 py-3">
                    <label for="id_tags">Теги <span class="text-danger">*</span></label>
                    <div class="row" id="id_tags">
                        {% for tag in tags %}
                            <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-2">
                                <input type="checkbox" value="{{ tag.id }}" id="id_tags_{{ tag.id }}" name="tags" >
                                <label for="id_tags_{{ tag.id }}">{{ tag.title }}</label>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-12 mb-4">
                    <label for="id_tags">Контетн <span class="text-danger">*</span></label>
                    <textarea name="content" id="id_tags" class="form-control" rows="5" required></textarea>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-success w-100">Добавить</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/my_news/my_news.html
{% extends 'base.html' %}
{% block title %}| Личный кабинет{% endblock title %}
{% block content %}

  <div class="album py-5 bg-light">
    <div class="container py-4">  
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <h3 class="mb-5">Welcome {{ request.user.first_name }} {{ request.user.last_name }}</h3>


        <h4>Ваши материалы:</h4>    
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for item in news %}
                <div class="col">
                <div class="card shadow-sm h-100">
                    <a href="{% url 'item_news' id=item.id %}"><img src="{{ item.image.url }}" alt="" class="w-100"></a>
                    <div class="card-body">
                    <p class="card-text"><a href="{% url 'item_news' id=item.id %}">{{ item.title }}</a> </p>
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <small class="text-muted">{{ item.views }} просмотров</small>
                    </div>
                    <div>Категория: {{ item.category.title }}</div>
                    <div>
                        <span>Теги:</span>
                        {% for tag in item.tags.all %}
                                <a href="{% url 'filter_news_by_tags' id=tag.id  %}">{{ tag.title }}</a> /
                        {% endfor %}
                    </div>
                    <div>
                        <span>Автор:</span> 
                        <span>{{ item.author.first_name }} {{ item.author.last_name }}</span>
                    </div>
                    </div>
                </div>
                </div>
                {% empty %}
                <p>Empty!</p>
            {% endfor %}
            </div>
        </div>
    </div>
  </div>

  <div class="panel"><a href="{% url 'create_news' %}">Добавить новости <i class="fa-solid fa-circle-plus"></i></a></div>

{% endblock content %}

templates/my_news/update_news.html
{% extends 'base.html' %}
{% block title %}| Редактирование новостей{% endblock title %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container py-5">  
        <h3 class="mb-5 text-center">Редактирование новостей</h3>

        <form action="{% url 'update_news' id=news.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-12 mb-3">
                    <label for="id_title">Заголовок <span class="text-danger">*</span></label>
                    <input type="text" name="title" id="id_title" class="form-control" value="{{ news.title }}" required>
                </div> 
                <div class="col-md-6 col-12">
                    <label for="id_iamge">Выбрать новое изображение</label>
                    <input type="file" name="image" class="form-control" id="id_iamge">
                </div>
                <div class="col-md-6 col-12">
                    <label for="id_category">Категория <span class="text-danger">*</span></label>
                    <select name="category" class="form-control" id="id_category required">
                        <option disabled>Выберите категорию</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}"  {% if category.id == news.category.id %}selected{% endif %} >{{ category.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-12 py-3">
                    <label for="id_tags">Теги <span class="text-danger">*</span></label>
                    <div class="row" id="id_tags">
                        {% for tag in tags %}
                            <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-2">
                                <input type="checkbox" value="{{ tag.id }}" {% if tag in news.tags.all %}checked{% endif %} id="id_tags_{{ tag.id }}" name="tags" >
                                <label for="id_tags_{{ tag.id }}">{{ tag.title }}</label>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-12 mb-4">
                    <label for="id_tags">Контетн <span class="text-danger">*</span></label>
                    <textarea name="content" id="id_tags" class="form-control" rows="5" required>{{ news.content }}</textarea>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-warning w-100">Изменить</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}